name: Pylint

on: [push]

jobs:
  build:
    environment: base
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LLM: ${{ envs.LLM }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        python ./.github/workflows/do_linting.py
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: krauhen
        author_email: henning.krause90@gmail.com
        add: '*.py --force'
        message: 'AI-linted code from pylint and OpenAI(${{ envs.LLM }})'
        new_branch: auto-pylinted
        push: origin auto-pylinted --force
